#!/bin/dash

find dist/ -exec bash -c 'printf "%q\n" "$@"' sh {} + | grep -v "Calculator.wasm\$\|.gitignore\|CNAME\|dist/\$\|dist/up_/img\$\|dist/up_/img/icons\$\|icons/site.webmanifest" | xargs -r rm -r
